apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: video-processor-link-api-ingress
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: video-processor-link-api-svc
                port:
                  number: 80
