apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: video-processor-link-api
    newName: REPLACE_ME_ECR_LINK_API_REPOSITORY_URL
    newTag: latest
