apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-processor-link-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-processor-link-api
  template:
    metadata:
      labels:
        app: video-processor-link-api
    spec:
      containers:
        - name: api
          image: video-processor-link-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: link-api-config
            - secretRef:
                name: link-api-secrets
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
